<a href="https://colab.research.google.com/github/BrezginaVera/Python_libraries/blob/main/Homework_lession3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Задание 1
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd 
from sklearn.datasets import load_boston
boston = load_boston()
data = boston["data"]
feature_names = boston["feature_names"]
target = boston["target"]
X = pd.DataFrame(data, columns=feature_names)
Y = pd.DataFrame(target, columns=['price'])
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, random_state=42)
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, Y_train)
Y_pred = lr.predict(X_test)
Y_pred.shape
test = pd.DataFrame({
    "Y_test": Y_test["price"],
    "Y_pred": Y_pred.flatten()
})
from sklearn.metrics import r2_score
r2_score(Y_test, Y_pred)
#Значение R2 = 0.7112260057484974

0.7112260057484974

In [7]:
#Задание 2
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor (n_estimators = 1000, max_depth = 12, random_state = 42)
model.fit(X_train, Y_train.values[:,0])
Y_pred_2 = model.predict(X_test)
test_2 = pd.DataFrame({
    "Y_test": Y_test["price"],
    "Y_pred_2": Y_pred_2
})
r2_score(Y_test, Y_pred_2)
#Значение R2 = 0.87472606157312, эта модель работает лучше 

0.87472606157312

In [15]:
#Задание 3
print(model.feature_importances_)
model.feature_importances_.sum()
max_value_1 = model.feature_importances_.argmax()
max_value_1
max_value_2 = 0
max_value = model.feature_importances_[max_value_2]
for i in range (model.n_features_):
  if max_value < model.feature_importances_[i] and i!=max_value_1:
    max_value = model.feature_importances_[i]
    max_value_2 = i
print(max_value_2)

[0.03167574 0.00154252 0.00713813 0.00123624 0.01426897 0.40268179
 0.01429864 0.06397257 0.00528122 0.01152493 0.01808108 0.01245085
 0.41584732]
5


In [16]:
#Задание 4
from google.colab import drive 
drive.mount ('/content/drive')
#!ls "/content/drive/My Drive"
path = "/content/drive/MyDrive/creditcard.csv"

Mounted at /content/drive


In [17]:
df = pd.read_csv(path)
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
df.value_counts(normalize=True)
pd.options.display.max_columns = 100
#df.info()
#df.head(10)
X = df.drop("Class", axis = 1)
y = pd.Series(df["Class"])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100, stratify=y)
X_train.shape
X_test.shape
y_train.shape
y_test.shape
parameters = [{'n_estimators': [10, 15],
'max_features': np.arange(3, 5),
'max_depth': np.arange(4, 7)}]
model = GridSearchCV(estimator=RandomForestClassifier(random_state=100), param_grid=parameters, scoring = 'roc_auc', cv=3)
model.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=RandomForestClassifier(random_state=100),
             param_grid=[{'max_depth': array([4, 5, 6]),
                          'max_features': array([3, 4]),
                          'n_estimators': [10, 15]}],
             scoring='roc_auc')

In [18]:
model.best_params_

{'max_depth': 6, 'max_features': 3, 'n_estimators': 15}

In [19]:
y_pred = model.predict_proba(X_train)
y_pred_proba = y_pred[:,1]

In [20]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, y_pred_proba[:85443])

0.47962888734329023

In [21]:
#Дополнительные задания 
from sklearn.datasets import load_wine
data = load_wine()
data_keys = data.keys()
data_keys

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [22]:
print(data["data"])

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [23]:
print(data["feature_names"])

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


In [24]:
print(data["DESCR"])
#Имеем 3 класса:class_0, class_1, class_2

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [25]:
X = pd.DataFrame(data["data"], columns=data["feature_names"])
X.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [26]:
X.shape

(178, 13)

In [27]:
X.info()
#Пропущенных значеий нет

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
dtypes: fl

In [28]:
data["target"]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [29]:
X["Target"] = data["target"]

In [30]:
X_corr = X.corr(method='pearson')
X_corr.head()

alcohol  malic_acid       ash  alcalinity_of_ash  \
alcohol            1.000000    0.094397  0.211545          -0.310235   
malic_acid         0.094397    1.000000  0.164045           0.288500   
ash                0.211545    0.164045  1.000000           0.443367   
alcalinity_of_ash -0.310235    0.288500  0.443367           1.000000   
magnesium          0.270798   -0.054575  0.286587          -0.083333   

                   magnesium  total_phenols  flavanoids  nonflavanoid_phenols  \
alcohol             0.270798       0.289101    0.236815             -0.155929   
malic_acid         -0.054575      -0.335167   -0.411007              0.292977   
ash                 0.286587       0.128980    0.115077              0.186230   
alcalinity_of_ash  -0.083333      -0.321113   -0.351370              0.361922   
magnesium           1.000000       0.214401    0.195784             -0.256294   

                   proanthocyanins  color_intensity       hue  \
alcohol                   0.136698         0.546364 -0.071747   
malic_acid               -0.220746         0.248985 -0.561296   
ash                       0.009652         0.258887 -0.074667   
alcalinity_of_ash        -0.197327         0.018732 -0.273955   
magnesium                 0.236441         0.199950  0.055398   

                   od280/od315_of_diluted_wines   proline    Target  
alcohol                                0.072343  0.643720 -0.328222  
malic_acid                            -0.368710 -0.192011  0.437776  
ash                                    0.003911  0.223626 -0.049643  
alcalinity_of_ash                     -0.276769 -0.440597  0.517859  
magnesium                              0.066004  0.393351 -0.209179

In [34]:
high_corr = X_corr["Target"][np.abs(X_corr["Target"]) > 0.5].drop("Target", axis=0)
high_corr = list(high_corr.index)
print(high_corr)

['alcalinity_of_ash', 'total_phenols', 'flavanoids', 'hue', 'od280/od315_of_diluted_wines', 'proline']


In [35]:
X = X.drop("Target", axis=1)
X.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [38]:
for i in high_corr:
  X[i] = X[i]**2
  X["_2"]= X[i]
X.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43         59224.0896      127.0         7.8400   
1    13.20        1.78  2.14         15735.1936      100.0         7.0225   
2    13.16        2.36  2.67        119688.3216      101.0         7.8400   
3    14.37        1.95  2.50         79659.4176      113.0        14.8225   
4    13.24        2.59  2.87        194481.0000      118.0         7.8400   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity     hue  \
0      9.3636                  0.28             2.29             5.64  1.0816   
1      7.6176                  0.26             1.28             4.38  1.1025   
2     10.4976                  0.30             2.81             5.68  1.0609   
3     12.1801                  0.24             2.18             7.80  0.7396   
4      7.2361                  0.39             1.82             4.32  1.0816   

   od280/od315_of_diluted_wines    proline  alcalinity_of_ash_2  \
0                       15.3664  1134225.0               243.36   
1                       11.5600  1102500.0               125.44   
2                       10.0489  1404225.0               345.96   
3                       11.9025  2190400.0               282.24   
4                        8.5849   540225.0               441.00   

   total_phenols_2  flavanoids_2   hue_2  od280/od315_of_diluted_wines_2  \
0           7.8400        9.3636  1.0816                         15.3664   
1           7.0225        7.6176  1.1025                         11.5600   
2           7.8400       10.4976  1.0609                         10.0489   
3          14.8225       12.1801  0.7396                         11.9025   
4           7.8400        7.2361  1.0816                          8.5849   

   proline_2         _2  
0  1134225.0  1134225.0  
1  1102500.0  1102500.0  
2  1404225.0  1404225.0  
3  2190400.0  2190400.0  
4   540225.0   540225.0